//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 12:12:11 PM EDT 
//


package com.redhat.syseng.soleng.rhpam.model.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="process-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="process-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="process-version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="package" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="container-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dynamic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processes"
})
@XmlRootElement(name = "process-definitions")
public class ProcessDefinitions {

    @XmlElement(required = true)
    protected ProcessDefinitions.Processes processes;

    /**
     * Gets the value of the processes property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessDefinitions.Processes }
     *     
     */
    public ProcessDefinitions.Processes getProcesses() {
        return processes;
    }

    /**
     * Sets the value of the processes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessDefinitions.Processes }
     *     
     */
    public void setProcesses(ProcessDefinitions.Processes value) {
        this.processes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="process-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="process-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="process-version" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="package" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="container-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dynamic" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "processId",
        "processName",
        "processVersion",
        "_package",
        "containerId",
        "dynamic"
    })
    public static class Processes {

        @XmlElement(name = "process-id", required = true)
        protected String processId;
        @XmlElement(name = "process-name", required = true)
        protected String processName;
        @XmlElement(name = "process-version")
        protected float processVersion;
        @XmlElement(name = "package", required = true)
        protected String _package;
        @XmlElement(name = "container-id", required = true)
        protected String containerId;
        @XmlElement(required = true)
        protected String dynamic;

        /**
         * Gets the value of the processId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessId() {
            return processId;
        }

        /**
         * Sets the value of the processId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessId(String value) {
            this.processId = value;
        }

        /**
         * Gets the value of the processName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessName() {
            return processName;
        }

        /**
         * Sets the value of the processName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessName(String value) {
            this.processName = value;
        }

        /**
         * Gets the value of the processVersion property.
         * 
         */
        public float getProcessVersion() {
            return processVersion;
        }

        /**
         * Sets the value of the processVersion property.
         * 
         */
        public void setProcessVersion(float value) {
            this.processVersion = value;
        }

        /**
         * Gets the value of the package property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackage() {
            return _package;
        }

        /**
         * Sets the value of the package property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackage(String value) {
            this._package = value;
        }

        /**
         * Gets the value of the containerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContainerId() {
            return containerId;
        }

        /**
         * Sets the value of the containerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContainerId(String value) {
            this.containerId = value;
        }

        /**
         * Gets the value of the dynamic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDynamic() {
            return dynamic;
        }

        /**
         * Sets the value of the dynamic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDynamic(String value) {
            this.dynamic = value;
        }

    }

}
